//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kulinarybook.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeImages
    {
        public int ImageID { get; set; }
        public int RecipeID { get; set; }
        public string imagePath { get; set; }
    
        public virtual Recipes Recipes { get; set; }
    }
}
